defaults: &redis_defaults
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>

development:
  <<: *redis_defaults

test:
  <<: *redis_defaults

production:
  <<: *redis_defaults
  channel_prefix: rewards_api_production
