services:
  app:
    build: .
    ports:
      - '3000:3000'
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - DATABASE_URL=mysql2://root:password@db/my_rails_app_development
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    volumes:
      - .:/app # Mount the local directory into the container
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_rails_app_development
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - mynetwork

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      - DATABASE_URL=mysql2://root:password@db/my_rails_app_development
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
